build: off

environment:
  matrix:
    - job_name: Ubuntu
      appveyor_build_worker_image: Ubuntu2004
    - job_name: MacOS
      appveyor_build_worker_image: macos
    - job_name: Windows
      appveyor_build_worker_image: Visual Studio 2019
      CHERE_INVOKING: 1
      MSYSTEM: MINGW64

for:
  -
    matrix:
      only:
        - job_name: Ubuntu
    init:
      - sh: sudo apt-get install -y gcc-9 llvm-10 clang-10 libgmp-dev
      - sh: sudo update-alternatives
          --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9
          --slave /usr/bin/gcov gcov /usr/bin/gcov-9
      - sh: sudo update-alternatives
          --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-10 100
          --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-10
          --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-10
      - sh: sudo update-alternatives
          --install /usr/bin/clang clang /usr/bin/clang-10 100
    test_script:
      - sh: scripts/coverage_toolchains.sh

  -
    matrix:
      only:
        - job_name: MacOS
    test_script:
      - sh: scripts/coverage_toolchains.sh

  -
    matrix:
      only:
        - job_name: Windows
    test_script:
      - cmd: C:\msys64\usr\bin\bash -cl "./scripts/coverage_toolchains.sh"
