build: off

environment:
  matrix:
    - job_name: Linux
      appveyor_build_worker_image: Ubuntu2004
    # - job_name: MacOS
    #   appveyor_build_worker_image: macos
    # - job_name: Windows
    #   appveyor_build_worker_image: Visual Studio 2019

for:
  -
    matrix:
      only:
        - job_name: Linux
    init:
      - sh: sudo apt-get install -y gcov llvm libgmp-dev
    test_script:
      - sh: scripts/coverage_toolchains.sh
