build: off
clone_depth: 10

environment:
  matrix:
    - job_name: ubuntu
      appveyor_build_worker_image: Ubuntu2004
    - job_name: macos
      appveyor_build_worker_image: macos
    - job_name: windows
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: windows-mingw
      appveyor_build_worker_image: Visual Studio 2019
      CHERE_INVOKING: 1
      MSYSTEM: MINGW64
    - job_name: windows-cygwin
      appveyor_build_worker_image: Visual Studio 2019
      CYGWIN_NOWINPATH: 1
      SHELLOPTS: igncr

for:
  -
    matrix:
      only:
        - job_name: ubuntu
    init:
      - sh: sudo apt-get update
      - sh: sudo apt-get install -y gcc-9 llvm-10 clang-10 libgmp-dev libtommath-dev
      - sh: sudo update-alternatives
          --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9
          --slave /usr/bin/gcov gcov /usr/bin/gcov-9
      - sh: sudo update-alternatives
          --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-10 100
          --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-10
          --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-10
      - sh: sudo update-alternatives
          --install /usr/bin/clang clang /usr/bin/clang-10 100
    test_script:
      - sh: scripts/coverage_toolchains.sh

  -
    matrix:
      only:
        - job_name: macos
    init:
      - sh: brew update
      - sh: brew install gmp libtommath
    test_script:
      - sh: scripts/coverage_toolchains.sh

  -
    matrix:
      only:
        - job_name: windows
    init:
      - cmd: cd "C:\" && git clone "https://github.com/libtom/libtommath.git" --depth 1 && cd "libtommath"
      - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
      - cmd: nmake -f "makefile.msvc" install
    test_script:
      - cmd: set "INCLUDE=C:\devel\include;%INCLUDE%" && set "LIB=C:\devel\lib;%LIB%" && set "PATH=C:\devel\bin;%PATH%"
      - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
      - cmd: call "C:\Program Files\Git\bin\bash.exe" -l "%cd%\scripts\coverage_toolchains.sh"

  -
    matrix:
      only:
        - job_name: windows-mingw
    init:
      - cmd: >-
          C:\msys64\usr\bin\bash -cl "
          pacman --sync --noconfirm --needed
          make
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-llvm
          mingw-w64-x86_64-gmp
          mingw-w64-x86_64-libtommath
          "
    test_script:
      - cmd: C:\msys64\usr\bin\bash -l "%cd%\scripts\coverage_toolchains.sh"

  -
    matrix:
      only:
        - job_name: windows-cygwin
    init:
      - cmd: >-
          C:\cygwin64\setup-x86_64.exe --quiet-mode --only-site
          --site "https://mirrors.kernel.org/sourceware/cygwin"
          --root "C:\cygwin64"
          --local-package-dir "C:\cygwin64\var\cache\setup"
          --packages "curl,cmake,make,gcc-g++,clang,llvm,libgmp-devel,libtommath-devel"
    test_script:
      - cmd: set "PATH="
      - cmd: C:\cygwin64\bin\bash -l "%cd%\scripts\coverage_toolchains.sh"
