language: c

dist: focal
osx_image: xcode12.2

jobs:
  include:
    - os: linux
      arch: amd64
    - os: osx
      arch: amd64

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
  homebrew:
    packages:
      - gmp

script:
  - scripts/toolchains.sh
