language: c

os:
  - linux
  - osx

dist: xenial
osx_image: xcode10.2

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libgmp-dev
  homebrew:
    packages:
      - gmp

script:
  - scripts/toolchains.sh
