language: c

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
  homebrew:
    packages:
      - gmp
    update: true

script:
  - scripts/toolchains.sh
