language: c

os:
  - linux
  - osx

dist: bionic

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
    update: true
  homebrew:
    packages:
      - gmp
    update: true

script:
  - scripts/toolchains.sh
