language: c

jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
    - os: linux
      arch: arm64
      dist: focal
    - os: osx
      arch: amd64
      osx_image: xcode12.2

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
  homebrew:
    packages:
      - gmp

script:
  - scripts/coverage_toolchains.sh
