language: c

jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
    - os: linux
      arch: arm64
      dist: focal

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev

script:
  - scripts/coverage_toolchains.sh
