language: c

os:
  - linux
  - osx

dist: xenial

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libgmp-dev
  homebrew:
    packages:
      - gmp

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo ln -s /usr/local/clang/libexec/ccc-analyzer /usr/local/bin/ccc-analyzer; fi

script:
  - scripts/toolchains.sh
