set (CMAKE_SYSTEM_NAME "Linux")

set (CMAKE_C_COMPILER "$ENV{TARGET}-gcc")
set (CMAKE_C_COMPILER_AR "$ENV{TARGET}-ar")
set (CMAKE_C_COMPILER_RANLIB "$ENV{TARGET}-ranlib")

set (CMAKE_FIND_ROOT_PATH "/usr/$ENV{TARGET}")
set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
