name: test

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y gcc-9 llvm-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 1
            --slave /usr/bin/gcov gcov /usr/bin/gcov-9
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 1
            --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-10

      - name: Coverage toolchains
        run: scripts/coverage_toolchains.sh
