name: test

on:
  - push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: |
          sudo apt-get install -y \
            gcc-9 llvm-10 clang-10 \
            libgmp-dev libtommath-dev
          sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 \
            --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 \
            --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-9
          sudo update-alternatives \
            --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-10 100 \
            --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-10 \
            --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-10
          sudo update-alternatives \
            --install /usr/bin/clang clang /usr/bin/clang-10 100

      - name: Coverage toolchains
        run: scripts/coverage_toolchains.sh

  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: brew install gmp libtommath

      - name: Coverage toolchains
        run: scripts/coverage_toolchains.sh

  windows-mingw:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 '{0}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-llvm
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-libtommath

      - name: Coverage toolchains
        run: scripts/coverage_toolchains.sh

  windows-cygwin:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Remove strawberryperl from PATH
        run: |
          if (Test-Path "C:\Strawberry") {
            Remove-Path "C:\Strawberry\c\bin"
            $env:path = $env:path.replace("C:\Strawberry\c\bin;", "")
          }
        shell: pwsh

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: C:\cygwin64
          packages: cmake make gcc-g++ clang llvm libgmp-devel libtommath-devel

      - name: Coverage toolchains
        run: C:\cygwin64\bin\bash.exe -l "%cd%\scripts\coverage_toolchains.sh"
        env:
          SHELLOPTS: igncr
