name: MacOS test

on:
  - push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Coverage toolchains
        run: scripts/coverage_toolchains.sh
